### ISSUE TITLE
provide specific glottocodes for underspecified varieties

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#11]
@Maunus, language varieties like Tepiman, Cahita, and Tarahumaran are all underspecified in terms of their glottocode. Do you happen to have an explicit variety for them, or could you outherwise provide geocoordinates?

**Comment by Maunus** [comment]
Well, they are proto-languages (my own reconstructions) and I don't think glottolog assigns glottocodes to protolanguages, right? That's why I just used the code for the language group.

**Comment by LinguList** [comment]
are ALL of them proto-languages? Aren't there three extant languages?

**Comment by Maunus** [comment]
Well, yes, but I don't include the data from the individual daughter varieties in this wordlist. It would be sort of misleading to attribute the reconstructed form to any of the daughter languages.

**Comment by LinguList** [comment]
So Cora, Huichol, Tepiman, etc. are all your reconstructions? That's what I mean, not the languages called "Proto-X". In that case, I'd say it is more accurate to call them Proto-X, as I'd use the term Proto-German for the ancestor of the German dialects or similar. It's just for clarification, as I do not know the languages...

**Comment by Maunus** [comment]
Huichol is fine since there is only one variety. For Cora it is Cora of Jesus María specifically, which oddly doesn't have a glottocode (Santa Teresa and Cora of el Nayar, which have glottocodes, are different varieties). 

I didn't include "proto-" prefixes for Tepiman, Cahitan and Tarahumaran since they are already names of language groupings not individual languages, and it is specified in the notes how I have reconstructed the forms.

**Comment by Maunus** [comment]
Tepiman is a portmanteau of Tepehuan and Pima, Cahitan is a name for the ancestor language of Yaqui and Mayo, and in Tarahumaran the final -n signals it is the larger grouping that includes Guarijío and not Tarahumara proper. But if you think it would be better to include the proto-specifically, then no problem.

**Comment by Maunus** [comment]
A turns out glottolog does have different varieties for Huichol, which is odd, since most sources consider it a single variety with no significant dialect variation. I have added the code sana1280 since most of the data from grimes is presumably from the San Andrés Cohamiata variety.

**Comment by Maunus** [comment]
And also a code for Cora of Jesus maria, it was buried under Cora of Nayar. I have added these codes, and the proto- prefix to the language csv file.
But I am still a little worried that it may be overly specific, since I do combine different sources, from some varieties and in some cases reconstruct proto-forms based on the,.

**Comment by LinguList** [comment]
Okay, thanks! Can you write an email to Harald Hammarström or go to the
github at https://github.com/glottolog/glottolog, to ask them to add a
new glottocode for the one variety? If the other three are
reconstructions, no worry, then we can close this issue, just wanted to
be sure (!). For the time being, could you maybe also provide a
geo-location for the Jesus María Cora? You can paste it here, I then add
it to languages.tsv

**Comment by LinguList** [comment]
excellent, thanks! This can be closed then!

**Comment by Maunus** [comment]
Yep. :)
